#!/usr/bin/env bash
set -u

case "${1-}" in
preview)
    row="$2"
    id="${row%%$'\t'*}"
    mime_type="$(cliphist list -fields mime "$id")" || exit
    if [[ "$mime_type" == image/* ]] || { [[ -z "$mime_type" ]] && printf '%s\n' "$row" | grep -qP '^\d+\t\[\[ binary data .* \]\]'; }; then
        cliphist decode "$id" | chafa -f sixel -s "${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}"
    elif [[ -z "$mime_type" || "$mime_type" == text/* ]]; then
        cliphist decode "$id"
    else
        printf '%s\n' "$row"
    fi
    ;;

*)
    row="$(cliphist list | fzf --preview "$(realpath "$0") preview {}")" || exit
    test -z "$row" && exit

    id="${row%%$'\t'*}"
    mime_type="$(cliphist list -fields mime "$id")" || exit
    copy_args=()
    if [[ -n "$mime_type" ]]; then
        copy_args=(--type "$mime_type")
    fi
    cliphist decode "$id" | wl-copy "${copy_args[@]}"
    ;;

esac
