#!/usr/bin/env bash

# executes same behaviour as below but with support for images
#
# cliphist list | wofi --dmenu | cliphist decode
#
# produces thumbnails and stores them in XDG_CACHE_HOME
# note: does NOT put in clipboard, call wl-copy yourself!

# set up thumbnail directory
thumb_dir="${XDG_CACHE_HOME:-$HOME/.cache}/cliphist/thumbs"
mkdir -p "$thumb_dir"

cliphist_list="$(cliphist list -fields id,format,preview)"

# delete thumbnails in cache but not in cliphist
for thumb in "$thumb_dir"/*; do
    clip_id="${thumb##*/}"
    clip_id="${clip_id%.*}"
    check=$(rg <<< "$cliphist_list" "^$clip_id\s")
    if [ -z "$check" ]; then
        >&2 rm -v "$thumb"
    fi
done

# remove unnecessary image tags
# create thumbnail if image not processed already
# print escape sequence
read -r -d '' prog <<EOF
\$3 ~ /^<meta http-equiv=/ { next }
\$2 != "" {
    image = \$1"."\$2
    system("[ -f $thumb_dir/"image" ] || cliphist decode "\$1" | magick - -resize '256x256>' $thumb_dir/"image )
    print "img:$thumb_dir/"image
    next
}
{ print \$1"\t"\$3 }
EOF

choice=$(gawk <<< $cliphist_list -F'\t' "$prog" | wofi -I --dmenu --cache-file=/dev/null -Dimage_size=100 -Dynamic_lines=true)

# stop execution if nothing selected in wofi menu
[ -z "$choice" ] && exit 1

if [ "${choice::4}" = "img:" ]; then
    clip_id="${choice##*/}"
    cliphist decode "${clip_id%.*}"
else
    cliphist decode <<<"$choice"
fi
