#!/bin/sh
# Outputs only unique lines and shows preview for the highlighted non-binary item

case "$1" in
	preview)
		id=$(echo "$2" | cut -f1)
		# show preview if non-binary data
		[ -n "$(cliphist list -fields format "$id")" ] || cliphist decode "$id"
		;;
	*)
		exec cliphist list |
			sort -k 2 -u | # sort by 2 field to the end of line and output only unique lines
			sort -nr |     # sort numerically in reverse
			fzf --preview "$(realpath "$0") preview {}" |
			cliphist decode |
			wl-copy
		;;
esac
