#!/usr/bin/env bash

tmp_dir="/tmp/cliphist"
rm -rf "$tmp_dir"

if [ -z "$1" ]; then
	mkdir -p "$tmp_dir"
	# When an image is copied from Firefox, some garbage text gets added to the clipboard too. We exclude that
	cliphist list | grep -E -v '<meta http-equiv="content-type" content="text/html; charset=utf-8"><img' | \
		while read data; do
			echo "$data" | grep 'binary data image' &>/dev/null
			if [ "$?" -eq 0 ] ; then
				fname="$(echo "$data" | cut -f1)"
				cliphist decode <<< "$data" >| "$tmp_dir"/"$fname".png &
				echo -en "$data\0icon\x1f$tmp_dir/$fname.png\n"
			else
				echo "$data"
			fi
		done
else
	cliphist decode <<<"$1" | wl-copy
fi
