#!/usr/bin/env bash
thumbnail_dir="${XDG_CACHE_HOME:-$HOME/.cache}/cliphist/thumbnails"
cliphist_list=$(cliphist list)
if [ -z "$cliphist_list" ]; then
  fuzzel -d --prompt-only "cliphist: nothing stored yet "
  rm -rf "$thumbnail_dir"
  exit
fi
[ -d "$thumbnail_dir" ] || mkdir -p "$thumbnail_dir"
read -r -d '' thumbnail <<EOF2
/^[0-9]+\s<meta http-equiv=/ { next }
match(\$0, /^([0-9]+)\s(\[\[\s)?binary.*(jpg|jpeg|png|bmp)/, grp) {
  cliphist_item_id=grp[1]
  ext=grp[3]
  thumbnail_file=cliphist_item_id"."ext
  system("[ -f ${thumbnail_dir}/"thumbnail_file" ] || echo " cliphist_item_id "\\\\\t | cliphist decode >${thumbnail_dir}/"thumbnail_file)
  print \$0"\0icon\x1f${thumbnail_dir}/"thumbnail_file
  next
}
1
EOF2
item=$(echo "$cliphist_list" | gawk "$thumbnail" | fuzzel -d --placeholder "Search clipboard..." --counter --no-sort --with-nth 2)
exit_code=$?
# ALT+0 to clear history
if [ "$exit_code" -eq 19 ]; then
  confirmation=$(echo -e "No\nYes" | fuzzel -d --placeholder "Wipe all history?" --lines 2)
  if [ "$confirmation" == "Yes" ]; then
    cliphist wipe
    rm -rf "$thumbnail_dir"
    notify-send "Clipboard" "History wiped" -t 1500
  fi
# ALT+1 to delete selected item
elif [ "$exit_code" -eq 10 ]; then
  if [ -n "$item" ]; then
    item_id=$(echo "$item" | cut -f1)
    echo "$item_id" | cliphist delete
    find "$thumbnail_dir" -name "${item_id}.*" -delete
    notify-send "Clipboard" "Entry deleted" -t 1500
  fi
else
  if [ -n "$item" ]; then
    echo "$item" | cliphist decode | wl-copy
    preview=$(echo "$item" | cut -f2 | cut -c1-60)
    notify-send "Copied" "$preview" -t 1500
  fi
fi
# Delete cached thumbnails no longer in cliphist db
find "$thumbnail_dir" -type f | while IFS= read -r thumbnail_file; do
  cliphist_item_id=$(basename "${thumbnail_file%.*}")
  if ! grep -q "^${cliphist_item_id}\s\[\[ binary data" <<<"$cliphist_list"; then
    rm "$thumbnail_file"
  fi
done
