#!/usr/bin/env bash

thumbnail_dir="${XDG_CACHE_HOME:-$HOME/.cache}/cliphist/thumbnails"

cliphist_list=$(cliphist list -fields id,format,preview)
if [ -z "$cliphist_list" ]; then
  fuzzel -d --prompt-only "cliphist: please store something first "
  rm -rf "$thumbnail_dir"
  exit
fi

[ -d "$thumbnail_dir" ] || mkdir -p "$thumbnail_dir"

# Write binary image to cache file if it doesn't exist
read -r -d '' thumbnail <<EOF
\$3 ~ /^<meta http-equiv=/ { next }
\$2 != "" {
  thumbnail_file=\$1"."\$2
  system("[ -f ${thumbnail_dir}/"thumbnail_file" ] || cliphist decode "\$1" >${thumbnail_dir}/"thumbnail_file)
  print \$1"\t"\$3"\0icon\x1f${thumbnail_dir}/"thumbnail_file
  next
}
{ print \$1"\t"\$3 }
EOF

item=$(echo "$cliphist_list" | gawk -F'\t' "$thumbnail" | fuzzel -d --placeholder "Search clipboard..." --counter --no-sort --with-nth 2)
exit_code=$?

# ALT+0 to clear history
if [ "$exit_code" -eq 19 ]; then
  confirmation=$(echo -e "No\nYes" | fuzzel -d --placeholder "Delete history?" --lines 2)
  [ "$confirmation" == "Yes" ] && rm ~/.cache/cliphist/db && rm -rf "$thumbnail_dir"
# ALT+1 to delete selected item
# configure the keybind with `custom-1` in your fuzzel.ini
elif [ "$exit_code" -eq 10 ]; then
  if [ -n "$item" ]; then
    item_id=$(echo "$item" | cut -f1)
    echo "$item_id" | cliphist delete
    find "$thumbnail_dir" -name "${item_id}.*" -delete
  fi
else
  [ -z "$item" ] || echo "$item" | cliphist decode | wl-copy
fi

# Delete cached thumbnails that are no longer in cliphist db
find "$thumbnail_dir" -type f | while IFS= read -r thumbnail_file; do
  cliphist_item_id=$(basename "${thumbnail_file%.*}")
  if ! grep -qP "^${cliphist_item_id}\t[^\t]" <<<"$cliphist_list"; then
    rm "$thumbnail_file"
  fi
done
