#!/usr/bin/env bash
set -u

case "${1-}" in
preview)
    row="$2"
    IFS=$'\t' read -r id _ <<<"$row"
    mime_type="$(cliphist list -fields mime "$id")" || exit
    case "$mime_type" in
    image/*) cliphist decode "$id" | chafa -f sixel -s "${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}" ;;
    text/*) cliphist decode "$id" ;;
    *) printf '%s\n' "$row" ;;
    esac
    ;;

*)
    row="$(cliphist list | fzf --preview "$(realpath "$0") preview {}")" || exit
    test -z "$row" && exit

    IFS=$'\t' read -r id _ <<<"$row"
    mime_type="$(cliphist list -fields mime "$id")" || exit
    copy_args=()
    if [[ -n "$mime_type" ]]; then
        copy_args=(--type "$mime_type")
    fi
    cliphist decode "$id" | wl-copy "${copy_args[@]}"
    ;;

esac
