#!/usr/bin/env bash

tmp_dir="/tmp/cliphist"
rm -rf "$tmp_dir"

if [[ -n "$1" ]]; then
    cliphist decode <<<"$1" | wl-copy
    exit
fi

mkdir -p "$tmp_dir"

read -r -d '' prog <<EOF
\$3 ~ /^<meta http-equiv=/ { next }
\$2 != "" {
    system("cliphist decode "\$1" >$tmp_dir/"\$1"."\$2)
    print \$1"\t"\$3"\0icon\x1f$tmp_dir/"\$1"."\$2
    next
}
{ print \$1"\t"\$3 }
EOF
cliphist list -fields id,format,preview | gawk -F'\t' "$prog"
