version: 2
multi-ecosystem-groups:
  all:
    schedule:
      interval: weekly
updates:
  - package-ecosystem: github-actions
    directory: /
    multi-ecosystem-group: all
    patterns: ["*"]
  - package-ecosystem: gomod
    directory: /
    multi-ecosystem-group: all
    patterns: ["*"]
