name: Lint and test
on:
  push:
    branches:
      - develop
  pull_request:
jobs:
  test:
    name: Lint and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          skip-go-installation: true
      - name: Test
        run: go test ./...
