name: Build and upload binaries
on:
  release:
    types: [created]
jobs:
  do-linux-amd64:
    name: linux/amd64
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
  do-linux-386:
    name: linux/386
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: 386
  do-linux-arm:
    name: linux/arm
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: arm
